<a href="https://colab.research.google.com/github/duguyihou/Cocococoa/blob/master/Week2_UTS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from sklearn.datasets import load_iris
import plotly.graph_objs as go
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import  train_test_split

COLAB = False
IRIS_EXPERIMENT_X_SPACE_QUNANTISATION_BIN_NUM = 50

def generate_all_X_space_normalised_samples_np(N):
  X0, X1 = np.meshgrid(np.arange(N), np.arange(N))
  
  return np.stack([X0.flatten(), X1.flatten()]).T / N

In [0]:
iris_db = load_iris()
all_x = generate_all_X_space_normalised_samples_np(IRIS_EXPERIMENT_X_SPACE_QUNANTISATION_BIN_NUM)

In [0]:
print(type(iris_db))

<class 'sklearn.utils.Bunch'>


In [0]:
iris_db?

In [0]:
dir(iris_db)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [0]:
type(iris_db.data), type(iris_db.target)

(numpy.ndarray, numpy.ndarray)

In [0]:
print(iris_db.data.shape, iris_db.target.shape)

(150, 4) (150,)


In [0]:
print(iris_db.data[:10],iris_db.target[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]] [0 0 0 0 0 0 0 0 0 0]


In [0]:
X, y = iris_db.data, iris_db.target

In [0]:
X_sub = []
y_sub = []
for i in range(len(iris_db.data)):
  if iris_db.target[i] == 0 or iris_db.target[i] == 1:
    X_sub.append(iris_db.data[i])
    y_sub.append(iris_db.target[i])

In [0]:
print(X_sub[0:5])
print(y_sub[0:5])

[array([5.1, 3.5, 1.4, 0.2]), array([4.9, 3. , 1.4, 0.2]), array([4.7, 3.2, 1.3, 0.2]), array([4.6, 3.1, 1.5, 0.2]), array([5. , 3.6, 1.4, 0.2])]
[0, 0, 0, 0, 0]


In [0]:
X_sub = np.array(X_sub)
y_sub = np.array(y_sub)
print(X_sub[0:5])
print(y_sub[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [0]:
X_sub = []
y_sub = []
for x_, y_ in zip(iris_db.data, iris_db.target):
  if y_ == 0 or y_ == 1:
    X_sub.append(x_)
    y_sub.append(y_)
X_sub = np.array(X_sub)
y_sub = np.array(y_sub)

In [0]:
X_sub = np.array([x_ for x_, y_ in zip(iris_db.data, iris_db.target) if y_ == 0 or y_ == 1])
y_sub = np.array([y_ for x_, y_ in zip(iris_db.data, iris_db.target) if y_ == 0 or y_ == 1])

In [0]:
X_sub = X[(y==0) + (y==1)]
y_sub = y[(y==0) + (y==1)]
X = X_sub
Y = y_sub

In [0]:
X = X[:, :2]

In [0]:
quant_num = IRIS_EXPERIMENT_X_SPACE_QUNANTISATION_BIN_NUM

data_bins = [[[] for a1 in range(quant_num)] for a2 in range(quant_num)]